### ISSUE TITLE
Reqeust : 유저 토큰 저장 테이블의 토큰 길이 연장

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#26]
### 제안사항

@axisotherwise 

저희가 OAuth 2.0 에 가깝게 구현하는 것을 작은 목표로 삼아서 MySQL 안에 토큰을 저장해두어야 하는데 길이 제한에 걸렸습니다.
기존에는 ***HS256*** 을 사용했었는데 아마도 이번에 ***RS256*** 을 사용하게 되면서 기본 길이 자체가 길게 나오는 것 같습니다.

payload 가 하나도 없어도 거의 440 ~ 480 길이 정도의 토큰이 나오기 때문에 해당 칼럼 길이를 ***VARCHAR(1000)*** 정도로 늘려야 안전하지 않을까 싶습니다!

```cmd
Error: Data too long for column 'refresh_token' at row 1
    at PromisePoolConnection.query (~\project\node_modules\mysql2\promise.js:93:22)
    at AuthRepository.<anonymous> (~\project\dist\routes\repositories\auth.repository.js:133:41)
    at step (~\project\dist\routes\repositories\auth.repository.js:33:23)
    at Object.next (~\project\dist\routes\repositories\auth.repository.js:14:53)
    at ~\project\dist\routes\repositories\auth.repository.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (~\project\dist\routes\repositories\auth.repository.js:4:12)
    at AuthRepository.updateUserRefreshTokenRowByUserId (~\project\dist\routes\repositories\auth.repository.js:126:97)
    at AuthService.<anonymous> (~\project\dist\routes\services\auth.service.js:127:56)    at step (~\project\dist\routes\services\auth.service.js:44:23) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sql: 'UPDATE 테이블-명 SET 토큰-칼럼명 = 토큰값 " WHERE 유저_PK= 값;',
  sqlState: '22001',
  sqlMessage: "Data too long for column '토큰-칼럼명n' at row 1"
}
```

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by axisotherwise** [comment]
오호
varchar와 text에 성능 차이는 없다는 의견이 많은 거 같아요. text로 저장하는 방법도 있는 거 같습니다!

**Comment by unchaptered** [comment]
> 오호 varchar와 text에 성능 차이는 없다는 의견이 많은 거 같아요. text로 저장하는 방법도 있는 거 같습니다!

해당 부분 한 번 검색해보고 코멘트 다시 올리겠습니다!

**Comment by unchaptered** [comment]
> > 오호 varchar와 text에 성능 차이는 없다는 의견이 많은 거 같아요. text로 저장하는 방법도 있는 거 같습니다!
> 
> 해당 부분 한 번 검색해보고 코멘트 다시 올리겠습니다!

아래 게시글 참고해보니, TEXT 가 성능 저하가 되는 부분도 어느 정도 있다고 하네요.
해당 부분 반영해서, 저희가 유기적으로 ***ALTER*** 쿼리문 등으로 길이 늘려가면 좋을 것 같아요!

- [Choosing Between VARCHAR and TEXT in MySQL](https://www.navicat.com/en/company/aboutus/blog/1308-choosing-between-varchar-and-text-in-mysql#:~:text=Some%20Differences%20Between%20VARCHAR%20and%20TEXT&text=The%20VAR%20in%20VARCHAR%20means,be%20part%20of%20an%20index.)
- [VARCHAR vs. TEXT for MySQL Databases
](https://blog.cpanel.com/varchar-vs-text-for-mysql-databases/)
