### ISSUE TITLE
Bug : MulterProvvider 의 bucket is required

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#34]
### 한 일

기존의 application/json 과 더미 imageUrl 로 만들어진 로직을 ***multipart/form-data*** 로 변경하는 작업을 진행하고 있습니다.
회원가입 도메인에서는 ***이미지 1장*** 만을 제한사항으로 받고 있기 때문에, 다음과 같이 연결해 보았습니다.

```typescript
import { Router } from "express";
import { preventLoginUserGuard } from "../../middlewares/guards/_.exporter";
import { applicationXWwwFormUrlencodedFilter } from "../../middlewares/filters/_.exporter";
import { MulterProvider } from "../../modules/_.loader";
import { AuthController } from "../controllers/_.exporter";

const authRouter: Router = Router();
authRouter.post("/signup",
   preventLoginUserGuard,
   new MulterProvider().uploadSingle().single('imageValue'),
   new AuthController().signup);

export default authRouter;
```

### 에러 내용

연결하고 나서 ***Ctrl + S***  를 하고 나니 다음과 같은 컴파일 에러가 나오고 있습니다.

```cmd
Error: bucket is required
    at new S3Storage (~\project\node_modules\multer-s3\index.js:114:29)
    at module.exports (~\project\node_modules\multer-s3\index.js:255:10)
    at MulterProvider.uploadSingle (~\project\dist\modules\providers\multer.provider.js:20:22)
    at Object.<anonymous> (~\project\dist\routes\routers\auth.router.js:9:96)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

### 조치 사항

> 현재 확인 중에 있습니다. -> 확인되었습니다.

문제 지점은 싱글턴 패턴이 정상 작동하지 않는 것으로 보입니다.

현재는 ***static isInit*** 변수와 ***static init*** 메서드를 이용해서 공급자 함수의 환경 변수를 제어하고 있습니다.

따라서 `~/server.ts` 파일에서 먼저 init 을 한 후에 공급자 함수의 인스턴스를 생성해서 각 클래스에서 사용 중입니다.

대다수의 모듈에서는 이러한 방식이 큰 문제가 없었으나, 미들웨어의 경우 ***컴파일 단계*** 에서 이미 ***new S3Client({})*** 가 호출되고 해당 시점에는 값이 undefined 일 것이므로 에러가 발생하고 있습니다.

그 증거로 MulterProvider.prototype.uploadSingle 메서드를 다음과 같이 변경하면 정상적으로 컴파일이 됩니다.

```typescript
return multer({
            storage: multerS3({
                s3,
                bucket: '임의값',
                contentType: multerS3.AUTO_CONTENT_TYPE,
                key(req, file, done) { /* 키 할당 로직*/ }
            }),
            fileFilter(req, file, done) { /* 필터링 로직 */ },
            limits: { fileSize: 파일 사이즈 제한 },
        });
```

따라서 컴파일 단계에서 바로 multerS3 가 호출되는 것을 막기 위해서 MulterProvider 의 구조를 고쳐야 할 것 같습니다.

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by axisotherwise** [comment]
```typescript    
    static uploadSingle: RequestHandler = (req, res, next) => {
        return this.test().single("img")(req, res, next);
    }

    static test = () => {
        const s3 = new S3Client({
            credentials: {
                accessKeyId: MulterProvider.S3_ACCESS_KEY,
                secretAccessKey: MulterProvider.S3_SECRET_KEY,
            },
            region: MulterProvider.REGION,
        });

        return multer({
            storage: multerS3({
                s3,
                bucket: MulterProvider.BUCKET,
                key(req, file, done) {
                    done(null, `profile/${Date.now()}${file.originalname}`);
                },
            }),
            fileFilter(req, file, done) {
                if (file.mimetype === "image/png" || file.mimetype === "image/jpg" || file.mimetype === "image/jpeg") {
                    done(null, true);
                } else {
                    // 에러 처리 추후 고민
                    return done(new Error("error"));
                }
            },
            limits: { fileSize: 5 * 1024 * 1024 },
        });
    }
```
MulterProvider 공급자에 기존 private로 사용하던 메서드를 static으로 수정하고 미들웨어 확장 방식을 이용하여 사용하였으나 클래스의 확장성을 고려하면 더 좋은 방법이 있을 거 같아요.

**Comment by unchaptered** [comment]
너무 감사합니다!
이 부분은 저희 ***기술 피드백*** 받으면서 더 좋은 방향에 대한 키워드가 있으면, 해당 방향 구글링해서 리펙터링 하면 좋을 것 같네요.
