### ISSUE TITLE
Bug : regex should not use global or sticky mode

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#42]
### 한 일

저희 데이터 모델링 파일 [링크](https://global-giraffe-ef7.notion.site/1-_-0827-c90106a9886846a8bf42d37be9a77706) 보면서 놓친 것 있나 확인해보니, nickname 과 passwor 에 정규표현식 적용하는 것을 뺴먹어서 해당 작업 진행하려고 했습니다.

### 에러 내용

아래와 같은 에러가 발생하고 있습니다.

```cmd
Error: regex should not use global or sticky mode
    at new module.exports (~\project\node_modules\@hapi\hoek\lib\error.js:23:19)
    at module.exports (~\project\node_modules\@hapi\hoek\lib\assert.js:21:11)
    at internals.Base.method (~\project\node_modules\joi\lib\types\string.js:539:17)
    at ~\project\dist\server.js:56:41
    at step (~\project\dist\server.js:33:23)
    at Object.next (~\project\dist\server.js:14:53)
    at ~\project\dist\server.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (~\project\dist\server.js:4:12)
    at ~\project\dist\server.js:43:23
```

### 조치 사항

현재 진행 중입니다.

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by unchaptered** [comment]
아래 글 보면 정규표현식에 ***g*** 옵션 사용 상의 거부 같네요.

- [Regular expressions with the global flag should be used with caution](https://rules.sonarsource.com/typescript/RSPEC-6351)

**Comment by unchaptered** [comment]
***g*** 옵션을 뺴고 기능 구현을 완료해서 일시적으로 해당 이슈를 닫도록 하겠습니다.
