### ISSUE TITLE
Bug : Email address is not verified. The following identities failed the check in region AWS-SES-REGION: 수신자이메일@gmail.com

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#87]
### 한 일

기존에 ***이메일 인증 시스템*** 을 완성했는데, 어드민 으로 등록되어있는 email 을 제외한 사람의 email 은 ***이메일 발송이 거부*** 되는 문제가 발생하고 있습니다.

### 에러 내용

```cmd
MessageRejected: UnknownError
    at deserializeAws_queryMessageRejectedResponse (~\node_modules\@aws-sdk\client-ses\dist-cjs\protocols\Aws_query.js:3560:23)
    at deserializeAws_querySendEmailCommandError (~\node_modules\@aws-sdk\client-ses\dist-cjs\protocols\Aws_query.js:2561:25)  
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ~\node_modules\@aws-sdk\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24
    at async ~\node_modules\@aws-sdk\middleware-signing\dist-cjs\middleware.js:11:20
    at async StandardRetryStrategy.retry (~\node_modules\@aws-sdk\middleware-retry\dist-cjs\StandardRetryStrategy.js:51:46)    
    at async ~\node_modules\@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:6:22 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '식별자-ID',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  xmlns: 'http://ses.amazonaws.com/doc/2010-12-01/',
  Error: {
    Type: 'Sender',
    Code: 'MessageRejected',
    Message: 'Email address is not verified. The following identities failed the check in region AWS-SES-REGION 수신자-EMAIL'
  },
  RequestId: '식별자-ID'
}
```

### 조치 사항

만약 조치한 것이 있거나 구글링한 게 있다면, ...

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by unchaptered** [comment]
***AWS SES*** 를 심사를 받아야지, ***일반 사용자*** 한테 메일을 보낼 수 있었습니다.
따라서, 다른 팀원 분들의 이메일을 등록하고 발송을 하니 성공했습니다.

@axisotherwise

**Comment by unchaptered** [comment]
우측에 표기된 순서대로 AWS SES  에 ***verified email*** 을 등록을 했는데, ***1 / 2 / 3 / 5*** 는 이메일이 전송이 되었습니다.
그리고 그 나머지 이메일에는 동일한 에러가 발생하기 시작했습니다.

![image](https://user-images.githubusercontent.com/86306802/188919714-d4f08744-6ff2-413a-a144-704b60ed5acf.png)

```cmd
Email address is not verified. The following identities failed the check in region
AWS-SES-REGION: 수신자이메일@gmail.com
```
